name: Natto CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Cache .m2 directory
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/project.clj') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Install dependencies
      run: lein deps

    - name: Install clj-kondo
      run: curl -sL https://raw.githubusercontent.com/clj-kondo/clj-kondo/master/script/install-clj-kondo | bash -s -- --dir /usr/local/bin

    - name: Run clj-kondo
      run: clj-kondo --lint src

    - name: Test with Leiningen
      run: lein test

    - name: Build with Leiningen
      run: lein uberjar
      
